apiVersion: Config Sync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/brandon-blackline/acm-test
    branch: main
    dir: root-sync
