apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-2"
  name: pubsubtopic-sample
  namespace: config-control
spec:
  schemaSettings:
    schemaRef:
      name: pubsubtopic-dep
    encoding: JSON